// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package models

import (
	"context"

	"github.com/google/uuid"
)

const cateogryExists = `-- name: CateogryExists :one
select Exists(select id, parent_id, name, slug, logo_class from categories where slug = $1)
`

func (q *Queries) CateogryExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, cateogryExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteCategory = `-- name: DeleteCategory :exec
delete from categories where id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const listCategories = `-- name: ListCategories :many
select id, parent_id, name, slug, logo_class from categories
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.LogoClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
