// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"github.com/google/uuid"
)

type Category struct {
	ID        uuid.UUID
	ParentID  uuid.NullUUID
	Name      string
	Slug      string
	LogoClass string
}
