// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID
	ParentID  pgtype.UUID
	Name      string
	Slug      string
	LogoClass string
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type User struct {
	ID                 pgtype.UUID
	GoogleID           string
	Email              string
	Username           string
	AvatarUrl          pgtype.Text
	PhoneNumber        pgtype.Text
	PhoneVerified      bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	LastUsernameChange pgtype.Timestamp
}
