// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (google_id, email, username, phone_number, avatar_url)
    VALUES ($1, $2, $3, $4, $5)
RETURNING id, google_id, email, username, avatar_url, phone_number, phone_verified, created_at, updated_at, last_username_change
`

type CreateUserParams struct {
	GoogleID    string
	Email       string
	Username    string
	PhoneNumber pgtype.Text
	AvatarUrl   pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.GoogleID,
		arg.Email,
		arg.Username,
		arg.PhoneNumber,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Username,
		&i.AvatarUrl,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsernameChange,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, email, username, avatar_url, phone_number, phone_verified, created_at, updated_at, last_username_change
FROM users
WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Username,
		&i.AvatarUrl,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsernameChange,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_id, email, username, avatar_url, phone_number, phone_verified, created_at, updated_at, last_username_change
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Username,
		&i.AvatarUrl,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsernameChange,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE
    users
SET avatar_url = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID        pgtype.UUID
	AvatarUrl pgtype.Text
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	return err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE
    users
SET username = $2,
    updated_at = now(),
    last_username_change = now()
WHERE id = $1
RETURNING id, google_id, email, username, avatar_url, phone_number, phone_verified, created_at, updated_at, last_username_change
`

type UpdateUsernameParams struct {
	ID       pgtype.UUID
	Username string
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUsername, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Username,
		&i.AvatarUrl,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsernameChange,
	)
	return i, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS (
        SELECT 1
        FROM users
        WHERE username = $1)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
